version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: certificate-generator:dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app:cached
      - /app/node_modules
